version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Build completed
      - aws s3 cp --recursive build/ s3://intaskbucket/
artifacts:
  files:
    - '**/*'
  base-directory: build

